php:
  preset: laravel
<<<<<<< HEAD
=======
  version: 8
>>>>>>> origin/master
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
